Digamon,
Manon-og

# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [3]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 666.0 kB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [267]:
import numpy as np

#### 2. Print the numpy version

In [170]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [169]:
arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [7]:
arr1 = np.zeros(15)
arr1[6] = 1

print(arr1)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [8]:
matrix = np.arange(16).reshape(4, 4) 

print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [9]:
arr2 = np.array([1,2,4,0,4,0])
x = np.where(arr2 != 0)

print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [10]:
matrix1 = np.random.randint(0, 1000, (4, 4, 4))

print(matrix1)

[[[513 953 899 471]
  [112 979 795 823]
  [222 604 512 528]
  [340 453 319 126]]

 [[709 736 136 747]
  [620   0 562 423]
  [506 919 274 494]
  [415 305  20  27]]

 [[ 69  62 265 957]
  [251   3 822  31]
  [171 910 314 682]
  [539 879 466 679]]

 [[192 645 976 550]
  [210 910 632 889]
  [101 636 837 438]
  [666  96 595 269]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [11]:
matrix2 = np.random.randint(0, 1000, (15, 15))

print(matrix1)

[[[513 953 899 471]
  [112 979 795 823]
  [222 604 512 528]
  [340 453 319 126]]

 [[709 736 136 747]
  [620   0 562 423]
  [506 919 274 494]
  [415 305  20  27]]

 [[ 69  62 265 957]
  [251   3 822  31]
  [171 910 314 682]
  [539 879 466 679]]

 [[192 645 976 550]
  [210 910 632 889]
  [101 636 837 438]
  [666  96 595 269]]]


In [12]:
matrix2 = np.random.randint(0, 100, (4, 4, 4))
minValue = np.min(matrix2)
maxValue = np.max(matrix2)

print("minValue: ", minValue)
print("maxValue: ", maxValue)
print(matrix2)

minValue:  4
maxValue:  99
[[[96 66 51 50]
  [94 64 48 88]
  [57 20 54 25]
  [ 4 82 27 93]]

 [[55 88 74 39]
  [39 36  7 99]
  [49 76 69 43]
  [10 67 84 29]]

 [[23 27 58 60]
  [98 19 99 11]
  [19 53 21 18]
  [19 79 79 21]]

 [[56 64 16 38]
  [26  9 87 24]
  [49 53  7 86]
  [66 29  9 18]]]


#### 9. Create a random array of size 25 and find the mean value

In [13]:
matrix3 = np.random.randint(0, 1000, (25))
meanValue = np.mean(matrix3)

print("meanValue:", meanValue)
print(matrix3)

meanValue: 501.72
[712 908 393 929 506 905 149  85 273 257  90  49  69 924 409 826 934 494
 440 462 639 944 165 670 311]


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [14]:
arr3 = np.array([2,4,9])
arr4 = np.array([1,14,6])

print(arr3)
print(arr4)

[2 4 9]
[ 1 14  6]


10.1 What is the result of *a + b*?

In [ ]:
arr3 = np.array([2,4,9])
arr4 = np.array([1,14,6])

Sum = arr3 + arr4

print(arr3)
print(arr4)
print(Sum)

10.2 What is the result of *a - b*?

In [15]:
arr3 = np.array([2,4,9])
arr4 = np.array([1,14,6])

Dif = arr3 - arr4

print(arr3)
print(arr4)
print(Dif)

[2 4 9]
[ 1 14  6]
[  1 -10   3]


10.3 What is the result of *a × b*?

In [154]:
arr3 = np.array([2,4,9])
arr4 = np.array([1,14,6])

Mul = arr3 * arr4

print(arr3)
print(arr4)
print(Mul)

[2 4 9]
[ 1 14  6]
[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [17]:
arr3 = np.array([2,4,9])
arr4 = np.array([1,14,6])

Div = arr3 / arr4

print(arr3)
print(arr4)
print(Div)

[2 4 9]
[ 1 14  6]
[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [19]:
matrix4 = np.array([[10,20,30], [40,50,60], [70,80,90]])

print(matrix4)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [20]:
matrix4 = np.array([[10,20,30], [40,50,60], [70,80,90]])
element50 = matrix4[1,1]

print(element50)

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [22]:
matrix4 = np.array([[10,20,30], [40,50,60], [70,80,90]])
arr5 = matrix4[1]

print(arr5)

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [24]:
matrix4 = np.array([[10,20,30], [40,50,60], [70,80,90]])
arr5 = matrix4[0,2]
arr6 = matrix4[1,2]
arr7 = matrix4[2,2]
arr8 = np.array([arr5, arr6, arr7])

print(arr8)


[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [37]:
matrix4 = np.array([[10,20,30], [40,50,60], [70,80,90]])
matrix5 = matrix4[1:3, 1:]

print(matrix5)


[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [47]:
matrix6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(matrix6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [72]:
matrix6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix7 = matrix6[1:3, 1:3]

print(matrix7)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [84]:
matrix6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix7 = matrix6[0:1, 0:3:2]

print(matrix7)

[[1 3]]


4. Write code to reverse the order of rows in the matrix

In [90]:
matrix8 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix9 = matrix8[::-1, ::-1]

print(matrix9)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


5. Write code to extract the last two columns of the matrix.

In [99]:
matrix10 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix11 = matrix10[0:4, 2:4]

print(matrix7)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [104]:
arr9 = np.array([11,7,33])
arr10 = np.array([44,5,18])

print(arr9)
print(arr10)

[11  7 33]
[44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [106]:
arr11 = np.array([11,7,33])
arr12 = np.array([44,5,18])
arr13 = np.concatenate((arr11, arr12))

print(arr13)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [110]:
arr14 = np.array([11,7,33])
arr15 = np.array([44,5,18])
arr16 = np.stack((arr14, arr15), axis=1)

print(arr16)

[[11 44]
 [ 7  5]
 [33 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [161]:
arr17 = np.array([[1,2],[3,4]])
arr18 = np.array([[5,6],[7,8]])

print(arr17)
print(arr18)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [146]:
arr19 = np.array([[1,2],[3,4]])
arr20 = np.array([[5,6],[7,8]])
arr21 = np.hstack((arr19, arr20))

print(arr21)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [147]:
arr22 = np.array([[1,2],[3,4]])
arr23 = np.array([[5,6],[7,8]])
arr24 = np.vstack((arr22, arr23))

print(arr24)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [205]:
print("1st")
arr25 = np.arange(10,29) 
arr26 = arr25[::2]
print(arr26)


print("2nd")
arr27 = np.random.randint(1, 50, size=16).reshape(4, 4)  
print(arr27)

print("3rd")
arr28 = np.ones([2,3,4])
print(arr28)


1st
[10 12 14 16 18 20 22 24 26 28]
2nd
[[25 25  4 28]
 [16  3 24 19]
 [12 13 17 30]
 [ 8  8 41 28]]
3rd
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [211]:
print("1st")
arr29 = np.arange(10, 28)
arr30 = arr26.reshape(2, -1)
print(arr30)

print("2st")
arr31 = arr27[1]
print(arr31)

print("3rd")
value = -1
arr32 = np.where(arr31 % 2 == 0, value, arr31)
print(arr32)


1st
[[10 12 14 16 18]
 [20 22 24 26 28]]
2st
[16  3 24 19]
3rd
[-1  3 -1 19]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [220]:
print("1st")
mean = np.mean(arr27)
print("mean:", mean)
median = np.median(arr27)
print("median:", median)
standard = np.std(arr27)
print("standard:", standard)

print("2nd")
sumOfArr27 = np.sum(arr27[1])
print(arr27[1])
print("sumOfArr27:", sumOfArr27)

print("3rd")
maxValueOfArr27 = np.max(arr27)
print(arr27)
findMaxValue = np.where(arr27 == maxValueOfArr27)
print("maxValueOfArr27:", maxValueOfArr27)
print("located at",findMaxValue)

1st
mean: 18.8125
median: 18.0
standard: 10.260474830630404
2nd
[16  3 24 19]
sumOfArr27: 62
3rd
[[25 25  4 28]
 [16  3 24 19]
 [12 13 17 30]
 [ 8  8 41 28]]
maxValueOfArr27: 41
located at (array([3]), array([2]))


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [266]:
print("1st")
arr33 = np.random.rand(100)
arr34 = arr33.reshape(10, 10)
print(arr34)

print("2nd")
minValueOfArr34 = np.min(arr34)
print("minValueOfArr27:", minValueOfArr34)

print("3rd")
arr35 = np.sort(arr34.flatten())
arr36 = arr35[-5:]
print("they are:",arr36)
for i in range(5):
   index = np.where(arr34 == arr36[i])
   print(f"Top {5 - i} would be ",index)

1st
[[0.64792525 0.18105519 0.08370979 0.23432768 0.79374681 0.79880001
  0.61997895 0.43253364 0.6786279  0.11350349]
 [0.20229986 0.14693633 0.11784718 0.22262485 0.30697    0.11808054
  0.77856931 0.9950952  0.87306395 0.58486664]
 [0.99660965 0.38666236 0.56000393 0.21712862 0.34885094 0.87589463
  0.34366814 0.94695737 0.24651357 0.41036614]
 [0.64435159 0.75119159 0.78567881 0.97806977 0.53782565 0.35830306
  0.53423358 0.14075694 0.284583   0.13336495]
 [0.73258322 0.3639507  0.37019072 0.11677877 0.12085537 0.47947696
  0.26674044 0.96975626 0.48836604 0.1628459 ]
 [0.55239473 0.37269232 0.35405253 0.18622247 0.49085845 0.66995933
  0.17691916 0.29368087 0.89004671 0.96981218]
 [0.96012575 0.38970595 0.03507164 0.7912634  0.97516589 0.28032227
  0.30650713 0.33701988 0.2406445  0.43660554]
 [0.15400296 0.37465662 0.29087831 0.73578319 0.8875189  0.18852057
  0.85579366 0.14903994 0.81893225 0.81792336]
 [0.38322027 0.36074095 0.03470522 0.24863653 0.08517747 0.96543386
  0.7993